---
title: "ASO splitsampling error metrics"
author: "Dominik Schneider"
output:
  html_document:
    fig_height: 12
    fig_width: 30
    self_contained: true
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(raster)
library(rgdal)
library(tidyverse)
library(cowplot)
library(viridis)
library(broom)
library(viridis)
library(cowplot)
library(RColorBrewer)
library(knitr)

#must have rprojroot installed from devtools::install_github("krlmlr/rprojroot")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(cache=FALSE,echo=FALSE,message = FALSE,warning=FALSE,error=FALSE,hide=TRUE,results='hide')#,fig.height=12,fig.width=12)
```


```{r params}
ires='500m'
basin='tuo'
pathin='output/splitsample-modeling/20iterations/'
```

```{r data}
alldata=readRDS(paste0(pathin,'alldata_',ires,'.rds'))

predictions=readRDS(paste0(pathin,'stats_combined_',ires,'-withpctbias-phvmdlsonly.rds'))
```

# Error distribution of all aso dates

```{r allasodates,results='asis'}
mdlstats <-
  predictions %>%
  mutate(
    mdlpreds=factor(mdlpreds,levels=c('phv','phvfsca','phvaso','phvasofsca')),
    yr=substr(mdldte,1,4)
  ) %>%
  group_by(mdldte,asodte,mdlpreds)

mdlstats2 <- mdlstats %>%
  gather(metricvar,metricval,r2,pctmae,pctbias)
# mdlstats %>%
# filter(dte!=asodte)

mdlstats2 %>%
  group_by(mdlpreds,metricvar) %>%
  summarise(
    med=median(metricval,na.rm=TRUE),
    N=n()
  )  %>%
  spread(metricvar,med)  %>%
  knitr::kable(.,digits=2,scientific=F,
               caption = 'Median Statistics')

mdlstats2 %>%
  group_by(metricvar,mdlpreds) %>%
  summarise(
    avg=mean(metricval)) %>%
  spread(metricvar,avg) %>%
  knitr::kable(.,digits=2,scientific=F,
               caption= 'Mean Statistics')


mdlstats2 %>%
  group_by(metricvar,mdlpreds,yr) %>%
  summarise(
    avg=mean(metricval)) %>%
  spread(metricvar,avg) %>%
  knitr::kable(.,digits=2,scientific=F,
               caption= 'Yearl Mean Statistics')

# readr::write_tsv(path=paste0('output/avgmdlstats_phv-bootstrap_aso_',ires,'.txt'))


ggplot(mdlstats2)+
  geom_boxplot(aes(x=mdldte,y=metricval,fill=mdlpreds))+
  facet_grid(metricvar~yr,scales='free')+
  scale_fill_brewer(palette='Paired')+
  theme_bw(base_size=36)+
  theme(axis.text.x=element_text(angle=45,hjust=1),
        legend.justification=c(0,1),
        legend.position=c(0,1))

```

# Best Predictions from each model

```{r bestasodates}
bd_phvaso=read_tsv(paste0(pathin,'bestasodates_phvaso_',ires,'.txt'),col_types=cols(dte='c',bestasodte='c',bestrmse='d',bestpctrmse='d'))

bd_phvasofsca=read_tsv(paste0(pathin,'bestasodates_phvasofsca_',ires,'.txt'),col_types=cols(dte='c',bestasodte='c',bestrmse='d',bestpctrmse='d'))

```

```{r best_phvaso, results='asis'}
bestdates <-
  bind_rows(
    bd_phvaso %>% mutate(mdlpreds='phvaso'),
    bd_phvasofsca %>% mutate(mdlpreds='phvasofsca')
  )

bestpreds <-
  inner_join(mdlstats2,
             dplyr::select(bestdates,dte,bestasodte,mdlpreds),by=c('mdldte'='dte','asodte'='bestasodte','mdlpreds')) %>%
  ungroup %>%
  bind_rows(
    mdlstats2 %>% filter(!grepl('aso',mdlpreds))
  ) %>%
  mutate(mdlpreds=factor(mdlpreds,levels=c('phv','phvfsca','phvaso','phvasofsca')))

bestpreds %>%
  spread(metricvar,metricval) %>% 
  group_by(mdlpreds) %>% 
  # group_by(mdlpreds,metricvar) %>%
  summarise(
    mean(pctmae),
    sd(pctmae),
    mean(pctbias),
    sd(pctbias),
    mean(r2),
    sd(r2),
    N=n()
  ) %>% 
  knitr::kable(.,digits=2,scientific=F,
               caption='summary of predictsion from best aso date')

bestpreds %>%
  spread(metricvar,metricval) %>% 
  group_by(mdlpreds,yr) %>% 
  # group_by(mdlpreds,metricvar) %>%
  summarise(
    mean(pctmae),
    sd(pctmae),
    mean(pctbias),
    sd(pctbias),
    mean(r2),
    sd(r2),
    N=n()
  ) %>% 
  knitr::kable(.,digits=2,scientific=F,
               caption='yearly summary of predictsion from best aso date')


r2plt <- 
  bestpreds %>% 
  filter(metricvar=='r2') %>% 
ggplot()+
  geom_bar(aes(x=mdldte,y=metricval,fill=mdlpreds),stat='identity',position='dodge')+
  facet_wrap(~yr,scales='free_x')+
  scale_fill_brewer(palette='Paired')+
  coord_cartesian(ylim=c(0,1))+
  guides(fill=FALSE)+
  labs(x='Simulation Date',
       y=expression(r^2))+
  theme_bw()+
  theme(axis.text.x=element_text(angle=20,size=16,hjust=.8),
        axis.text.y=element_text(size=16),
        axis.title.x=element_text(size=18),
        axis.title.y=element_text(size=18),
        strip.background=element_blank(),
        strip.text=element_text(size=18,face='bold'),
        legend.justification=c(0,1),
        legend.position=c(0,1))

pctmaeplt <- 
bestpreds %>% 
  filter(metricvar=='pctmae') %>% 
ggplot()+
  geom_bar(aes(x=mdldte,y=metricval,fill=mdlpreds),stat='identity',position='dodge')+
  facet_wrap(~yr,scales='free_x')+
  scale_fill_brewer(palette='Paired',labels=c('PHV','PHV-FSCA','PHV-ASO','PHV-ASO-FSCA'))+
  guides(fill=guide_legend('Model Predictors'))+
    labs(x='Simulation Date',
       y='%MAE')+
  theme_bw()+
  theme(axis.text.x=element_text(angle=20,size=16,hjust=.8),
        axis.text.y=element_text(size=16),
        axis.title.x=element_text(size=18),
        axis.title.y=element_text(size=18),
        strip.background=element_blank(),
        strip.text=element_text(size=18,face='bold'),
        legend.justification=c(0,1),
        legend.position=c(0,1))

pgsplit <- plot_grid(r2plt,pctmaeplt,nrow=2,ncol=1,labels='auto',label_size=20)
  
save_plot(pgsplit,filename='figs/prederror_splitsample.pdf',
          nrow=4,
          ncol=1,
          base_width=12,
          base_aspect_ratio = .5)
```
